This is makeindex, version 2.15 [TeX Live 2014] (kpathsea + Thai support).
Scanning style file ./xjobb-en.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ./xjobb-en.acn....done (101 entries accepted, 0 rejected).
Sorting entries....done (799 comparisons).
Generating output file ./xjobb-en.acr....done (52 lines written, 0 warnings).
Output written in ./xjobb-en.acr.
Transcript written in ./xjobb-en.alg.
